import * as fs from "fs"
import * as util from "util"

export const
    accessAsync = fs.access ? util.promisify(fs.access) : undefined,
    appendFileAsync = fs.appendFile ? util.promisify(fs.appendFile) : undefined,
    chmodAsync = fs.chmod ? util.promisify(fs.chmod) : undefined,
    chownAsync = fs.chown ? util.promisify(fs.chown) : undefined,
    closeAsync = fs.close ? util.promisify(fs.close) : undefined,
    copyFileAsync = fs.copyFile ? util.promisify(fs.copyFile) : undefined,
    existsAsync = fs.exists ? util.promisify(fs.exists) : undefined,
    fchmodAsync = fs.fchmod ? util.promisify(fs.fchmod) : undefined,
    fchownAsync = fs.fchown ? util.promisify(fs.fchown) : undefined,
    fdatasyncAsync = fs.fdatasync ? util.promisify(fs.fdatasync) : undefined,
    fsyncAsync = fs.fsync ? util.promisify(fs.fsync) : undefined,
    ftruncateAsync = fs.ftruncate ? util.promisify(fs.ftruncate) : undefined,
    futimesAsync = fs.futimes ? util.promisify(fs.futimes) : undefined,
    lchmodAsync = fs.lchmod ? util.promisify(fs.lchmod) : undefined,
    lchownAsync = fs.lchown ? util.promisify(fs.lchown) : undefined,
    linkAsync = fs.link ? util.promisify(fs.link) : undefined,
    lutimesAsync = fs.lutimes ? util.promisify(fs.lutimes) : undefined,
    mkdirAsync = fs.mkdir ? util.promisify(fs.mkdir) : undefined,
    mkdtempAsync = fs.mkdtemp ? util.promisify(fs.mkdtemp) : undefined,
    openAsync = fs.open ? util.promisify(fs.open) : undefined,
    opendirAsync = fs.opendir ? util.promisify(fs.opendir) : undefined,
    readAsync = fs.read ? util.promisify(fs.read) : undefined,
    readdirAsync = fs.readdir ? util.promisify(fs.readdir) : undefined,
    readFileAsync = fs.readFile ? util.promisify(fs.readFile) : undefined,
    readlinkAsync = fs.readlink ? util.promisify(fs.readlink) : undefined,
    readvAsync = fs.readv ? util.promisify(fs.readv) : undefined,
    realpathAsync = fs.realpath ? util.promisify(fs.realpath) : undefined,
    renameAsync = fs.rename ? util.promisify(fs.rename) : undefined,
    rmAsync = fs.rm ? util.promisify(fs.rm) : undefined,
    rmdirAsync = fs.rmdir ? util.promisify(fs.rmdir) : undefined,
    symlinkAsync = fs.symlink ? util.promisify(fs.symlink) : undefined,
    truncateAsync = fs.truncate ? util.promisify(fs.truncate) : undefined,
    unlinkAsync = fs.unlink ? util.promisify(fs.unlink) : undefined,
    utimesAsync = fs.utimes ? util.promisify(fs.utimes) : undefined,
    writeAsync = fs.write ? util.promisify(fs.write) : undefined,
    writeFileAsync = fs.writeFile ? util.promisify(fs.writeFile) : undefined,
    writevAsync = fs.writev ? util.promisify(fs.writev) : undefined
